apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jarvis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jarvis
  template:
    metadata:
      labels:
        run: jarvis
    spec:
      containers:
      - image: jarvis:latest
        imagePullPolicy: IfNotPresent
        name: jarvis
---
apiVersion: v1
kind: Service
metadata:
  name: jarvis
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: jarvis
  type: NodePort
